#!/bin/bash
# Quick Start Guide for Lako PWA

echo "================================================"
echo "Lako PWA - Quick Start"
echo "================================================"
echo ""

# Check if we're in the right directory
if [ ! -f "frontend/index.html" ]; then
    echo "❌ Error: Please run this from the Lako project root directory"
    exit 1
fi

echo "✅ Project structure looks good"
echo ""
echo "=== PWA Files Created ==="
echo "✓ manifest.json - App metadata"
echo "✓ sw.js - Service worker for offline support"
echo "✓ js/pwa.js - PWA manager"
echo "✓ assets/images/logo.svg - App logo"
echo ""

echo "=== Next Steps ==="
echo ""
echo "1️⃣  Convert SVG Logo to PNG (Choose one method):"
echo ""
echo "   Method A: Online (Recommended)"
echo "   ├─ Go to: https://convertio.co/svg-png/"
echo "   ├─ Upload: frontend/assets/images/logo.svg"
echo "   └─ Download as:"
echo "      • logo-192.png (192x192)"
echo "      • logo-512.png (512x512)"
echo "      • logo-96.png (96x96)"
echo "      • logo-maskable-192.png (192x192)"
echo "      • logo-maskable-512.png (512x512)"
echo ""
echo "   Method B: Using ImageMagick"
echo "   └─ convert logo.svg -resize 192x192 logo-192.png"
echo ""
echo "   Save all PNG files to: frontend/assets/images/"
echo ""

echo "2️⃣  Start Development Server:"
echo ""
echo "   cd frontend"
echo "   python -m http.server 8080"
echo "   # or if using Python 2:"
echo "   # python -m SimpleHTTPServer 8080"
echo ""

echo "3️⃣  Test in Browser:"
echo ""
echo "   ├─ Open: http://localhost:8080"
echo "   ├─ DevTools (F12) → Application → Service Workers"
echo "   ├─ Verify service worker shows 'Active' status"
echo "   ├─ Go offline (DevTools → Network → Offline)"
echo "   └─ Reload page - should still work!"
echo ""

echo "4️⃣  Test PWA Installation:"
echo ""
echo "   Desktop Chrome:"
echo "   ├─ Look for install icon in address bar"
echo "   ├─ Click 'Install app'"
echo "   └─ App opens in standalone window"
echo ""
echo "   Mobile Chrome/Android:"
echo "   ├─ Menu → Install app"
echo "   └─ Or tap 'Add to home screen'"
echo ""

echo "5️⃣  For Production (HTTPS Required):"
echo ""
echo "   ├─ Update manifest.json start_url to your domain"
echo "   ├─ Enable HTTPS on your server"
echo "   ├─ Update service worker cache names if needed"
echo "   └─ Test again to verify offline works"
echo ""

echo "=== Troubleshooting ==="
echo ""
echo "❓ Service worker not showing?"
echo "   └─ Clear browser cache: Ctrl+Shift+Delete"
echo ""
echo "❓ Icons not loading?"
echo "   └─ Verify PNG files exist in assets/images/"
echo ""
echo "❓ App not installable?"
echo "   └─ Must use HTTPS or localhost for PWA features"
echo ""

echo "✨ Need more help? See PWA_SETUP.md"
echo ""
